/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as IndexImport } from './routes/index'
import { Route as TestsTestImport } from './routes/tests/$test'
import { Route as TestTestImport } from './routes/test/$test'
import { Route as ResultsTestImport } from './routes/results/$test'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TestsTestRoute = TestsTestImport.update({
  path: '/tests/$test',
  getParentRoute: () => rootRoute,
} as any)

const TestTestRoute = TestTestImport.update({
  path: '/test/$test',
  getParentRoute: () => rootRoute,
} as any)

const ResultsTestRoute = ResultsTestImport.update({
  path: '/results/$test',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/results/$test': {
      preLoaderRoute: typeof ResultsTestImport
      parentRoute: typeof rootRoute
    }
    '/test/$test': {
      preLoaderRoute: typeof TestTestImport
      parentRoute: typeof rootRoute
    }
    '/tests/$test': {
      preLoaderRoute: typeof TestsTestImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute,
  ResultsTestRoute,
  TestTestRoute,
  TestsTestRoute,
])

/* prettier-ignore-end */
